// Generated by gencpp from file msg/DepthData.msg
// DO NOT EDIT!


#ifndef MSG_MESSAGE_DEPTHDATA_H
#define MSG_MESSAGE_DEPTHDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg
{
template <class ContainerAllocator>
struct DepthData_
{
  typedef DepthData_<ContainerAllocator> Type;

  DepthData_()
    : depth(0.0)
    , pressure(0.0)
    , temp(0.0)  {
    }
  DepthData_(const ContainerAllocator& _alloc)
    : depth(0.0)
    , pressure(0.0)
    , temp(0.0)  {
  (void)_alloc;
    }



   typedef float _depth_type;
  _depth_type depth;

   typedef float _pressure_type;
  _pressure_type pressure;

   typedef float _temp_type;
  _temp_type temp;





  typedef boost::shared_ptr< ::msg::DepthData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg::DepthData_<ContainerAllocator> const> ConstPtr;

}; // struct DepthData_

typedef ::msg::DepthData_<std::allocator<void> > DepthData;

typedef boost::shared_ptr< ::msg::DepthData > DepthDataPtr;
typedef boost::shared_ptr< ::msg::DepthData const> DepthDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg::DepthData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg::DepthData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'msg': ['/home/pi/robotfish/src/msg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg::DepthData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg::DepthData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg::DepthData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg::DepthData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg::DepthData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg::DepthData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg::DepthData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c6ad25ee4a8b5281bb4c431c5fdf360e";
  }

  static const char* value(const ::msg::DepthData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc6ad25ee4a8b5281ULL;
  static const uint64_t static_value2 = 0xbb4c431c5fdf360eULL;
};

template<class ContainerAllocator>
struct DataType< ::msg::DepthData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg/DepthData";
  }

  static const char* value(const ::msg::DepthData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg::DepthData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 depth\n"
"float32 pressure\n"
"float32 temp\n"
;
  }

  static const char* value(const ::msg::DepthData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg::DepthData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
      stream.next(m.pressure);
      stream.next(m.temp);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DepthData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg::DepthData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg::DepthData_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "pressure: ";
    Printer<float>::stream(s, indent + "  ", v.pressure);
    s << indent << "temp: ";
    Printer<float>::stream(s, indent + "  ", v.temp);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_MESSAGE_DEPTHDATA_H
