// Generated by gencpp from file msg/MotionControl.msg
// DO NOT EDIT!


#ifndef MSG_MESSAGE_MOTIONCONTROL_H
#define MSG_MESSAGE_MOTIONCONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace msg
{
template <class ContainerAllocator>
struct MotionControl_
{
  typedef MotionControl_<ContainerAllocator> Type;

  MotionControl_()
    : motion()  {
    }
  MotionControl_(const ContainerAllocator& _alloc)
    : motion(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _motion_type;
  _motion_type motion;





  typedef boost::shared_ptr< ::msg::MotionControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::msg::MotionControl_<ContainerAllocator> const> ConstPtr;

}; // struct MotionControl_

typedef ::msg::MotionControl_<std::allocator<void> > MotionControl;

typedef boost::shared_ptr< ::msg::MotionControl > MotionControlPtr;
typedef boost::shared_ptr< ::msg::MotionControl const> MotionControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::msg::MotionControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::msg::MotionControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace msg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'msg': ['/home/pi/robotfish/src/msg/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::msg::MotionControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::msg::MotionControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg::MotionControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::msg::MotionControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg::MotionControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::msg::MotionControl_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::msg::MotionControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56c5b2babfc4b27e5a596091bb964bc2";
  }

  static const char* value(const ::msg::MotionControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56c5b2babfc4b27eULL;
  static const uint64_t static_value2 = 0x5a596091bb964bc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::msg::MotionControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "msg/MotionControl";
  }

  static const char* value(const ::msg::MotionControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::msg::MotionControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string motion\n"
;
  }

  static const char* value(const ::msg::MotionControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::msg::MotionControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotionControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::msg::MotionControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::msg::MotionControl_<ContainerAllocator>& v)
  {
    s << indent << "motion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.motion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MSG_MESSAGE_MOTIONCONTROL_H
