#!/usr/bin/env python
#encoding:utf-8

ADDR_ID = 7
BYTE_ID = 1

ADDR_BAUDRATE = 8
BYTE_BAUDRATE = 1

ADDR_DRIVE_MODE = 10
BYTE_DRIVE_MODE = 1

ADDR_OPERATING_MODE = 11
BYTE_OPERATING_MODE = 1
MODE_EXT_POS = 4
MODE_POSITION = 3
MODE_CURRENT = 0
MODE_VELOCITY = 1
MODE_PWM = 16

ADDR_PROTOCOL = 13
BYTE_PROTOCOL = 1

ADDR_VELOCITY_LIMIT = 44
BYTE_VELOCITY = 4

ADDR_TORQUE_ENABLE = 64
BYTE_TORQUE = 1

ADDR_P_POSITION = 80
ADDR_I_POSITION = 82
ADDR_D_POSITION = 84
BYTE_PID = 2

ADDR_GOAL_PWM = 100
BYTE_PWM = 2

ADDR_GOAL_CURRENT = 102
BYTE_CURRENT = 2

ADDR_GOAL_VELOCITY = 104

ADDR_GOAL_POSITION = 116
BYTE_POSITION = 4

ADDR_PROFILE_VELOCITY = 560
ADDR_PROFILE_ACCELORATE =  556
